// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_token.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTokenReq struct {
	DeviceId             *string  `protobuf:"bytes,1,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
	Channel              *string  `protobuf:"bytes,2,req,name=channel" json:"channel,omitempty"`
	Ts                   *uint64  `protobuf:"varint,3,req,name=ts" json:"ts,omitempty"`
	AppSecret            *string  `protobuf:"bytes,4,req,name=app_secret,json=appSecret" json:"app_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenReq) Reset()         { *m = GetTokenReq{} }
func (m *GetTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetTokenReq) ProtoMessage()    {}
func (*GetTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_84919a1bca4229d6, []int{0}
}

func (m *GetTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenReq.Unmarshal(m, b)
}
func (m *GetTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenReq.Marshal(b, m, deterministic)
}
func (m *GetTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenReq.Merge(m, src)
}
func (m *GetTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetTokenReq.Size(m)
}
func (m *GetTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenReq proto.InternalMessageInfo

func (m *GetTokenReq) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *GetTokenReq) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

func (m *GetTokenReq) GetTs() uint64 {
	if m != nil && m.Ts != nil {
		return *m.Ts
	}
	return 0
}

func (m *GetTokenReq) GetAppSecret() string {
	if m != nil && m.AppSecret != nil {
		return *m.AppSecret
	}
	return ""
}

type GetTokenRsp struct {
	Code                 *int32   `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Msg                  *string  `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
	Token                *string  `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	ExpiredTime          *uint64  `protobuf:"varint,4,opt,name=expired_time,json=expiredTime" json:"expired_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenRsp) Reset()         { *m = GetTokenRsp{} }
func (m *GetTokenRsp) String() string { return proto.CompactTextString(m) }
func (*GetTokenRsp) ProtoMessage()    {}
func (*GetTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_84919a1bca4229d6, []int{1}
}

func (m *GetTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRsp.Unmarshal(m, b)
}
func (m *GetTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRsp.Marshal(b, m, deterministic)
}
func (m *GetTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRsp.Merge(m, src)
}
func (m *GetTokenRsp) XXX_Size() int {
	return xxx_messageInfo_GetTokenRsp.Size(m)
}
func (m *GetTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRsp proto.InternalMessageInfo

func (m *GetTokenRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *GetTokenRsp) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *GetTokenRsp) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *GetTokenRsp) GetExpiredTime() uint64 {
	if m != nil && m.ExpiredTime != nil {
		return *m.ExpiredTime
	}
	return 0
}

func init() {
	proto.RegisterType((*GetTokenReq)(nil), "main.GetTokenReq")
	proto.RegisterType((*GetTokenRsp)(nil), "main.GetTokenRsp")
}

func init() { proto.RegisterFile("get_token.proto", fileDescriptor_84919a1bca4229d6) }

var fileDescriptor_84919a1bca4229d6 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xcd, 0x4a, 0x43, 0x31,
	0x10, 0x85, 0xb9, 0xb9, 0x29, 0x7a, 0xa7, 0xa2, 0x32, 0xb8, 0x08, 0x88, 0x10, 0xbb, 0xca, 0xca,
	0xd7, 0x10, 0xb7, 0xb1, 0xfb, 0x10, 0x92, 0xa1, 0x06, 0x9b, 0x1f, 0x6f, 0x06, 0xf1, 0xf1, 0xa5,
	0x69, 0x05, 0x77, 0xe7, 0x7c, 0x33, 0xf0, 0x1d, 0xb8, 0x3b, 0x10, 0x3b, 0xae, 0x9f, 0x54, 0x5e,
	0xda, 0x5a, 0xb9, 0xa2, 0xcc, 0x3e, 0x95, 0x5d, 0x87, 0xed, 0x2b, 0xf1, 0xfe, 0xc4, 0x2d, 0x7d,
	0xe1, 0x23, 0x2c, 0x91, 0xbe, 0x53, 0x20, 0x97, 0xa2, 0x9a, 0xb4, 0x30, 0x8b, 0xbd, 0x3e, 0x83,
	0xb7, 0x88, 0x0a, 0xae, 0xc2, 0x87, 0x2f, 0x85, 0x8e, 0x4a, 0x8c, 0xd3, 0x5f, 0xc5, 0x5b, 0x10,
	0xdc, 0xd5, 0xac, 0x85, 0x91, 0x56, 0x70, 0xc7, 0x27, 0x00, 0xdf, 0x9a, 0xeb, 0x14, 0x56, 0x62,
	0x25, 0xc7, 0xf3, 0xe2, 0x5b, 0x7b, 0x1f, 0x60, 0x77, 0xfc, 0x27, 0xed, 0x0d, 0x11, 0x64, 0xa8,
	0x91, 0x86, 0x6f, 0x63, 0x47, 0xc6, 0x7b, 0x98, 0x73, 0x3f, 0x5c, 0x3c, 0xa7, 0x88, 0x0f, 0xb0,
	0x19, 0xf3, 0xd5, 0xac, 0x27, 0xb3, 0xd8, 0x73, 0xc1, 0x67, 0xb8, 0xa1, 0x9f, 0x96, 0x56, 0x8a,
	0x8e, 0x53, 0x26, 0x25, 0xf5, 0x64, 0xa4, 0xdd, 0x5e, 0xd8, 0x3e, 0x65, 0xfa, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0xfd, 0xf2, 0x47, 0x37, 0xfa, 0x00, 0x00, 0x00,
}
