// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order_commit.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderCommit struct {
	DeviceId             *string              `protobuf:"bytes,1,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
	Version              *string              `protobuf:"bytes,2,req,name=version" json:"version,omitempty"`
	Ext                  *string              `protobuf:"bytes,3,opt,name=ext" json:"ext,omitempty"`
	Orders               []*OrderCommit_Order `protobuf:"bytes,4,rep,name=orders" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderCommit) Reset()         { *m = OrderCommit{} }
func (m *OrderCommit) String() string { return proto.CompactTextString(m) }
func (*OrderCommit) ProtoMessage()    {}
func (*OrderCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8b8fa6091c20fe3, []int{0}
}

func (m *OrderCommit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCommit.Unmarshal(m, b)
}
func (m *OrderCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCommit.Marshal(b, m, deterministic)
}
func (m *OrderCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCommit.Merge(m, src)
}
func (m *OrderCommit) XXX_Size() int {
	return xxx_messageInfo_OrderCommit.Size(m)
}
func (m *OrderCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCommit.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCommit proto.InternalMessageInfo

func (m *OrderCommit) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *OrderCommit) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *OrderCommit) GetExt() string {
	if m != nil && m.Ext != nil {
		return *m.Ext
	}
	return ""
}

func (m *OrderCommit) GetOrders() []*OrderCommit_Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type OrderCommit_Order struct {
	OrderId              *uint64                       `protobuf:"varint,1,req,name=order_id,json=orderId" json:"order_id,omitempty"`
	ImageUrlPrefix       *string                       `protobuf:"bytes,2,req,name=image_url_prefix,json=imageUrlPrefix" json:"image_url_prefix,omitempty"`
	OrderPhotos          *OrderCommit_Order_OrderPhoto `protobuf:"bytes,3,req,name=order_photos,json=orderPhotos" json:"order_photos,omitempty"`
	OrderStream          *uint64                       `protobuf:"varint,4,opt,name=order_stream,json=orderStream" json:"order_stream,omitempty"`
	ImageStream          *uint64                       `protobuf:"varint,5,opt,name=image_stream,json=imageStream" json:"image_stream,omitempty"`
	ThirdImageUrlSuffix  []string                      `protobuf:"bytes,6,rep,name=third_image_url_suffix,json=thirdImageUrlSuffix" json:"third_image_url_suffix,omitempty"`
	ImageSign            *string                       `protobuf:"bytes,7,opt,name=image_sign,json=imageSign" json:"image_sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *OrderCommit_Order) Reset()         { *m = OrderCommit_Order{} }
func (m *OrderCommit_Order) String() string { return proto.CompactTextString(m) }
func (*OrderCommit_Order) ProtoMessage()    {}
func (*OrderCommit_Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8b8fa6091c20fe3, []int{0, 0}
}

func (m *OrderCommit_Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCommit_Order.Unmarshal(m, b)
}
func (m *OrderCommit_Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCommit_Order.Marshal(b, m, deterministic)
}
func (m *OrderCommit_Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCommit_Order.Merge(m, src)
}
func (m *OrderCommit_Order) XXX_Size() int {
	return xxx_messageInfo_OrderCommit_Order.Size(m)
}
func (m *OrderCommit_Order) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCommit_Order.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCommit_Order proto.InternalMessageInfo

func (m *OrderCommit_Order) GetOrderId() uint64 {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return 0
}

func (m *OrderCommit_Order) GetImageUrlPrefix() string {
	if m != nil && m.ImageUrlPrefix != nil {
		return *m.ImageUrlPrefix
	}
	return ""
}

func (m *OrderCommit_Order) GetOrderPhotos() *OrderCommit_Order_OrderPhoto {
	if m != nil {
		return m.OrderPhotos
	}
	return nil
}

func (m *OrderCommit_Order) GetOrderStream() uint64 {
	if m != nil && m.OrderStream != nil {
		return *m.OrderStream
	}
	return 0
}

func (m *OrderCommit_Order) GetImageStream() uint64 {
	if m != nil && m.ImageStream != nil {
		return *m.ImageStream
	}
	return 0
}

func (m *OrderCommit_Order) GetThirdImageUrlSuffix() []string {
	if m != nil {
		return m.ThirdImageUrlSuffix
	}
	return nil
}

func (m *OrderCommit_Order) GetImageSign() string {
	if m != nil && m.ImageSign != nil {
		return *m.ImageSign
	}
	return ""
}

type OrderCommit_Order_OrderPhoto struct {
	SuccessGpsTime       []uint64 `protobuf:"varint,1,rep,name=success_gps_time,json=successGpsTime" json:"success_gps_time,omitempty"`
	FailGpsTime          []uint64 `protobuf:"varint,2,rep,name=fail_gps_time,json=failGpsTime" json:"fail_gps_time,omitempty"`
	VideoLostGpsTime     []uint64 `protobuf:"varint,3,rep,name=video_lost_gps_time,json=videoLostGpsTime" json:"video_lost_gps_time,omitempty"`
	VideoDeletedGpsTime  []uint64 `protobuf:"varint,4,rep,name=video_deleted_gps_time,json=videoDeletedGpsTime" json:"video_deleted_gps_time,omitempty"`
	FramedFailedGpsTime  []uint64 `protobuf:"varint,5,rep,name=framed_failed_gps_time,json=framedFailedGpsTime" json:"framed_failed_gps_time,omitempty"`
	UploadFailedGpsTime  []uint64 `protobuf:"varint,6,rep,name=upload_failed_gps_time,json=uploadFailedGpsTime" json:"upload_failed_gps_time,omitempty"`
	UnknownReasonGpsTime []uint64 `protobuf:"varint,7,rep,name=unknown_reason_gps_time,json=unknownReasonGpsTime" json:"unknown_reason_gps_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCommit_Order_OrderPhoto) Reset()         { *m = OrderCommit_Order_OrderPhoto{} }
func (m *OrderCommit_Order_OrderPhoto) String() string { return proto.CompactTextString(m) }
func (*OrderCommit_Order_OrderPhoto) ProtoMessage()    {}
func (*OrderCommit_Order_OrderPhoto) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8b8fa6091c20fe3, []int{0, 0, 0}
}

func (m *OrderCommit_Order_OrderPhoto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCommit_Order_OrderPhoto.Unmarshal(m, b)
}
func (m *OrderCommit_Order_OrderPhoto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCommit_Order_OrderPhoto.Marshal(b, m, deterministic)
}
func (m *OrderCommit_Order_OrderPhoto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCommit_Order_OrderPhoto.Merge(m, src)
}
func (m *OrderCommit_Order_OrderPhoto) XXX_Size() int {
	return xxx_messageInfo_OrderCommit_Order_OrderPhoto.Size(m)
}
func (m *OrderCommit_Order_OrderPhoto) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCommit_Order_OrderPhoto.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCommit_Order_OrderPhoto proto.InternalMessageInfo

func (m *OrderCommit_Order_OrderPhoto) GetSuccessGpsTime() []uint64 {
	if m != nil {
		return m.SuccessGpsTime
	}
	return nil
}

func (m *OrderCommit_Order_OrderPhoto) GetFailGpsTime() []uint64 {
	if m != nil {
		return m.FailGpsTime
	}
	return nil
}

func (m *OrderCommit_Order_OrderPhoto) GetVideoLostGpsTime() []uint64 {
	if m != nil {
		return m.VideoLostGpsTime
	}
	return nil
}

func (m *OrderCommit_Order_OrderPhoto) GetVideoDeletedGpsTime() []uint64 {
	if m != nil {
		return m.VideoDeletedGpsTime
	}
	return nil
}

func (m *OrderCommit_Order_OrderPhoto) GetFramedFailedGpsTime() []uint64 {
	if m != nil {
		return m.FramedFailedGpsTime
	}
	return nil
}

func (m *OrderCommit_Order_OrderPhoto) GetUploadFailedGpsTime() []uint64 {
	if m != nil {
		return m.UploadFailedGpsTime
	}
	return nil
}

func (m *OrderCommit_Order_OrderPhoto) GetUnknownReasonGpsTime() []uint64 {
	if m != nil {
		return m.UnknownReasonGpsTime
	}
	return nil
}

type OrderCommitResp struct {
	Code                 *int32                       `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	DeviceId             *string                      `protobuf:"bytes,2,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
	Msg                  *string                      `protobuf:"bytes,3,req,name=msg" json:"msg,omitempty"`
	OrderResps           []*OrderCommitResp_OrderResp `protobuf:"bytes,4,rep,name=order_resps,json=orderResps" json:"order_resps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *OrderCommitResp) Reset()         { *m = OrderCommitResp{} }
func (m *OrderCommitResp) String() string { return proto.CompactTextString(m) }
func (*OrderCommitResp) ProtoMessage()    {}
func (*OrderCommitResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8b8fa6091c20fe3, []int{1}
}

func (m *OrderCommitResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCommitResp.Unmarshal(m, b)
}
func (m *OrderCommitResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCommitResp.Marshal(b, m, deterministic)
}
func (m *OrderCommitResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCommitResp.Merge(m, src)
}
func (m *OrderCommitResp) XXX_Size() int {
	return xxx_messageInfo_OrderCommitResp.Size(m)
}
func (m *OrderCommitResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCommitResp.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCommitResp proto.InternalMessageInfo

func (m *OrderCommitResp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *OrderCommitResp) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *OrderCommitResp) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *OrderCommitResp) GetOrderResps() []*OrderCommitResp_OrderResp {
	if m != nil {
		return m.OrderResps
	}
	return nil
}

type OrderCommitResp_OrderResp struct {
	OrderId              *uint64  `protobuf:"varint,1,req,name=order_id,json=orderId" json:"order_id,omitempty"`
	CommitStatus         *int32   `protobuf:"varint,2,req,name=commit_status,json=commitStatus" json:"commit_status,omitempty"`
	Msg                  *string  `protobuf:"bytes,3,req,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCommitResp_OrderResp) Reset()         { *m = OrderCommitResp_OrderResp{} }
func (m *OrderCommitResp_OrderResp) String() string { return proto.CompactTextString(m) }
func (*OrderCommitResp_OrderResp) ProtoMessage()    {}
func (*OrderCommitResp_OrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8b8fa6091c20fe3, []int{1, 0}
}

func (m *OrderCommitResp_OrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCommitResp_OrderResp.Unmarshal(m, b)
}
func (m *OrderCommitResp_OrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCommitResp_OrderResp.Marshal(b, m, deterministic)
}
func (m *OrderCommitResp_OrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCommitResp_OrderResp.Merge(m, src)
}
func (m *OrderCommitResp_OrderResp) XXX_Size() int {
	return xxx_messageInfo_OrderCommitResp_OrderResp.Size(m)
}
func (m *OrderCommitResp_OrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCommitResp_OrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCommitResp_OrderResp proto.InternalMessageInfo

func (m *OrderCommitResp_OrderResp) GetOrderId() uint64 {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return 0
}

func (m *OrderCommitResp_OrderResp) GetCommitStatus() int32 {
	if m != nil && m.CommitStatus != nil {
		return *m.CommitStatus
	}
	return 0
}

func (m *OrderCommitResp_OrderResp) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderCommit)(nil), "main.OrderCommit")
	proto.RegisterType((*OrderCommit_Order)(nil), "main.OrderCommit.Order")
	proto.RegisterType((*OrderCommit_Order_OrderPhoto)(nil), "main.OrderCommit.Order.OrderPhoto")
	proto.RegisterType((*OrderCommitResp)(nil), "main.OrderCommitResp")
	proto.RegisterType((*OrderCommitResp_OrderResp)(nil), "main.OrderCommitResp.OrderResp")
}

func init() { proto.RegisterFile("order_commit.proto", fileDescriptor_f8b8fa6091c20fe3) }

var fileDescriptor_f8b8fa6091c20fe3 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x56, 0xfc, 0x93, 0xd4, 0x93, 0xb6, 0x44, 0x5b, 0xd4, 0x9a, 0x22, 0x84, 0x09, 0x17, 0x5f,
	0x28, 0x52, 0x2b, 0xee, 0x48, 0xfc, 0x29, 0x12, 0x12, 0xd5, 0x06, 0x8e, 0x68, 0x65, 0xc5, 0x9b,
	0x74, 0x85, 0xed, 0xb5, 0x76, 0xd7, 0xa1, 0x6f, 0xc1, 0x99, 0xa7, 0xe3, 0x29, 0xb8, 0xa3, 0x9d,
	0x5d, 0xd7, 0x29, 0x11, 0x5c, 0xa2, 0xf1, 0xf7, 0x33, 0xf3, 0x65, 0x35, 0x03, 0x44, 0xaa, 0x92,
	0x2b, 0xb6, 0x92, 0x75, 0x2d, 0xcc, 0x45, 0xab, 0xa4, 0x91, 0x24, 0xaa, 0x0b, 0xd1, 0xcc, 0x7f,
	0x8e, 0x61, 0xfa, 0xc9, 0x92, 0x6f, 0x90, 0x23, 0x8f, 0x21, 0x29, 0xf9, 0x56, 0xac, 0x38, 0x13,
	0x65, 0x3a, 0xca, 0x82, 0x3c, 0xa1, 0x07, 0x0e, 0x58, 0x94, 0x24, 0x85, 0xc9, 0x96, 0x2b, 0x2d,
	0x64, 0x93, 0x06, 0x48, 0xf5, 0x9f, 0x64, 0x06, 0x21, 0xbf, 0x35, 0x69, 0x98, 0x8d, 0xf2, 0x84,
	0xda, 0x92, 0xbc, 0x84, 0x31, 0x0e, 0xd5, 0x69, 0x94, 0x85, 0xf9, 0xf4, 0xf2, 0xec, 0xc2, 0xce,
	0xbb, 0xd8, 0x99, 0xe5, 0x6a, 0xea, 0x65, 0xe7, 0x3f, 0x62, 0x88, 0x11, 0x21, 0x8f, 0xe0, 0xc0,
	0xe5, 0xf5, 0x11, 0x22, 0x3a, 0xc1, 0xef, 0x45, 0x49, 0x72, 0x98, 0x89, 0xba, 0xd8, 0x70, 0xd6,
	0xa9, 0x8a, 0xb5, 0x8a, 0xaf, 0xc5, 0xad, 0x8f, 0x72, 0x8c, 0xf8, 0x17, 0x55, 0x5d, 0x23, 0x4a,
	0xde, 0xc1, 0xa1, 0x6b, 0xd2, 0xde, 0x48, 0x23, 0x75, 0x1a, 0x66, 0x41, 0x3e, 0xbd, 0x9c, 0xff,
	0x23, 0x85, 0xfb, 0xbd, 0xb6, 0x52, 0x3a, 0x95, 0x77, 0xb5, 0x26, 0xcf, 0xfa, 0x36, 0xda, 0x28,
	0x5e, 0xd4, 0x69, 0x94, 0x8d, 0xf2, 0xc8, 0x4b, 0x96, 0x08, 0x59, 0x89, 0xcb, 0xe4, 0x25, 0xb1,
	0x93, 0x20, 0xe6, 0x25, 0x57, 0x70, 0x6a, 0x6e, 0x84, 0x2a, 0xd9, 0x10, 0x5e, 0x77, 0x6b, 0x1b,
	0x7e, 0x9c, 0x85, 0x79, 0x42, 0x4f, 0x90, 0x5d, 0xf8, 0x7f, 0xb0, 0x44, 0x8a, 0x3c, 0x01, 0xf0,
	0x7d, 0xc5, 0xa6, 0x49, 0x27, 0xf8, 0xb4, 0x89, 0xeb, 0x2a, 0x36, 0xcd, 0xf9, 0xaf, 0x00, 0x60,
	0x48, 0x6d, 0x5f, 0x46, 0x77, 0xab, 0x15, 0xd7, 0x9a, 0x6d, 0x5a, 0xcd, 0x8c, 0xa8, 0x79, 0x3a,
	0xca, 0xc2, 0x3c, 0xa2, 0xc7, 0x1e, 0xff, 0xd0, 0xea, 0xcf, 0xa2, 0xe6, 0x64, 0x0e, 0x47, 0xeb,
	0x42, 0x54, 0x83, 0x2c, 0x40, 0xd9, 0xd4, 0x82, 0xbd, 0xe6, 0x05, 0x9c, 0x6c, 0x45, 0xc9, 0x25,
	0xab, 0xa4, 0x36, 0x83, 0x32, 0x44, 0xe5, 0x0c, 0xa9, 0x8f, 0x52, 0x9b, 0x5e, 0x7e, 0x05, 0xa7,
	0x4e, 0x5e, 0xf2, 0x8a, 0x1b, 0x5e, 0x0e, 0x8e, 0x08, 0x1d, 0xae, 0xd9, 0x5b, 0x47, 0xee, 0x98,
	0xd6, 0xaa, 0xa8, 0x79, 0xc9, 0xec, 0xe4, 0x5d, 0x53, 0xec, 0x4c, 0x8e, 0x7d, 0x8f, 0xe4, 0x8e,
	0xa9, 0x6b, 0x2b, 0x59, 0xec, 0x9b, 0xc6, 0xce, 0xe4, 0xd8, 0xfb, 0xa6, 0x57, 0x70, 0xd6, 0x35,
	0xdf, 0x1a, 0xf9, 0xbd, 0x61, 0x8a, 0x17, 0x5a, 0x36, 0x83, 0x6b, 0x82, 0xae, 0x87, 0x9e, 0xa6,
	0xc8, 0x7a, 0xdb, 0xfc, 0xf7, 0x08, 0x1e, 0xec, 0x6c, 0x0a, 0xe5, 0xba, 0x25, 0x04, 0xa2, 0x95,
	0x2c, 0x39, 0xee, 0x65, 0x4c, 0xb1, 0xbe, 0x7f, 0x33, 0xc1, 0x5f, 0x37, 0x33, 0x83, 0xb0, 0xd6,
	0x1b, 0x5c, 0xbf, 0x84, 0xda, 0x92, 0xbc, 0x06, 0xb7, 0x3e, 0x4c, 0x71, 0xdd, 0xf6, 0xe7, 0xf1,
	0x74, 0x6f, 0x31, 0xed, 0x38, 0x7f, 0x22, 0x5c, 0xb7, 0x14, 0x64, 0x5f, 0xea, 0xf3, 0xaf, 0x90,
	0xdc, 0x11, 0xff, 0xbb, 0x96, 0xe7, 0x70, 0xe4, 0x4e, 0x9e, 0x69, 0x53, 0x98, 0x4e, 0x63, 0xb8,
	0x98, 0x1e, 0x3a, 0x70, 0x89, 0xd8, 0x7e, 0xc0, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x56, 0x8d,
	0xf6, 0xe0, 0x2e, 0x04, 0x00, 0x00,
}
