// Code generated by protoc-gen-go. DO NOT EDIT.
// source: third_pic.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PicReq struct {
	DeviceId             *string             `protobuf:"bytes,1,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
	OrderId              *uint64             `protobuf:"varint,2,req,name=order_id,json=orderId" json:"order_id,omitempty"`
	ImageInfo            []string            `protobuf:"bytes,3,rep,name=image_info,json=imageInfo" json:"image_info,omitempty"`
	ExpireTime           *string             `protobuf:"bytes,4,req,name=expire_time,json=expireTime" json:"expire_time,omitempty"`
	ClientId             *string             `protobuf:"bytes,5,req,name=client_id,json=clientId" json:"client_id,omitempty"`
	Host                 *string             `protobuf:"bytes,6,opt,name=host" json:"host,omitempty"`
	ImageDetailList      []*PicReq_ImageInfo `protobuf:"bytes,7,rep,name=image_detail_list,json=imageDetailList" json:"image_detail_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PicReq) Reset()         { *m = PicReq{} }
func (m *PicReq) String() string { return proto.CompactTextString(m) }
func (*PicReq) ProtoMessage()    {}
func (*PicReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_061d97f05d307286, []int{0}
}

func (m *PicReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicReq.Unmarshal(m, b)
}
func (m *PicReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicReq.Marshal(b, m, deterministic)
}
func (m *PicReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicReq.Merge(m, src)
}
func (m *PicReq) XXX_Size() int {
	return xxx_messageInfo_PicReq.Size(m)
}
func (m *PicReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PicReq.DiscardUnknown(m)
}

var xxx_messageInfo_PicReq proto.InternalMessageInfo

func (m *PicReq) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *PicReq) GetOrderId() uint64 {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return 0
}

func (m *PicReq) GetImageInfo() []string {
	if m != nil {
		return m.ImageInfo
	}
	return nil
}

func (m *PicReq) GetExpireTime() string {
	if m != nil && m.ExpireTime != nil {
		return *m.ExpireTime
	}
	return ""
}

func (m *PicReq) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *PicReq) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *PicReq) GetImageDetailList() []*PicReq_ImageInfo {
	if m != nil {
		return m.ImageDetailList
	}
	return nil
}

type PicReq_ImageInfo struct {
	Timestamp            *string  `protobuf:"bytes,1,req,name=timestamp" json:"timestamp,omitempty"`
	Uri                  *string  `protobuf:"bytes,2,req,name=uri" json:"uri,omitempty"`
	Auth                 *string  `protobuf:"bytes,3,req,name=auth" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PicReq_ImageInfo) Reset()         { *m = PicReq_ImageInfo{} }
func (m *PicReq_ImageInfo) String() string { return proto.CompactTextString(m) }
func (*PicReq_ImageInfo) ProtoMessage()    {}
func (*PicReq_ImageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_061d97f05d307286, []int{0, 0}
}

func (m *PicReq_ImageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicReq_ImageInfo.Unmarshal(m, b)
}
func (m *PicReq_ImageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicReq_ImageInfo.Marshal(b, m, deterministic)
}
func (m *PicReq_ImageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicReq_ImageInfo.Merge(m, src)
}
func (m *PicReq_ImageInfo) XXX_Size() int {
	return xxx_messageInfo_PicReq_ImageInfo.Size(m)
}
func (m *PicReq_ImageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PicReq_ImageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PicReq_ImageInfo proto.InternalMessageInfo

func (m *PicReq_ImageInfo) GetTimestamp() string {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return ""
}

func (m *PicReq_ImageInfo) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

func (m *PicReq_ImageInfo) GetAuth() string {
	if m != nil && m.Auth != nil {
		return *m.Auth
	}
	return ""
}

type PicRsp struct {
	Code                 *int32   `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Msg                  *string  `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PicRsp) Reset()         { *m = PicRsp{} }
func (m *PicRsp) String() string { return proto.CompactTextString(m) }
func (*PicRsp) ProtoMessage()    {}
func (*PicRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_061d97f05d307286, []int{1}
}

func (m *PicRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PicRsp.Unmarshal(m, b)
}
func (m *PicRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PicRsp.Marshal(b, m, deterministic)
}
func (m *PicRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PicRsp.Merge(m, src)
}
func (m *PicRsp) XXX_Size() int {
	return xxx_messageInfo_PicRsp.Size(m)
}
func (m *PicRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PicRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PicRsp proto.InternalMessageInfo

func (m *PicRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *PicRsp) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*PicReq)(nil), "main.PicReq")
	proto.RegisterType((*PicReq_ImageInfo)(nil), "main.PicReq.ImageInfo")
	proto.RegisterType((*PicRsp)(nil), "main.PicRsp")
}

func init() { proto.RegisterFile("third_pic.proto", fileDescriptor_061d97f05d307286) }

var fileDescriptor_061d97f05d307286 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xcd, 0x4e, 0xc3, 0x30,
	0x10, 0x84, 0xd5, 0x24, 0xfd, 0xf1, 0xf6, 0x50, 0xf0, 0x01, 0x99, 0x3f, 0x11, 0xf5, 0x94, 0x53,
	0x0e, 0x3c, 0x02, 0xe2, 0x12, 0x09, 0x09, 0x64, 0x71, 0x8f, 0xa2, 0x78, 0xdb, 0xac, 0x14, 0xc7,
	0xc1, 0x76, 0x11, 0x4f, 0xc8, 0x73, 0x21, 0xdb, 0x14, 0x6e, 0xe3, 0x6f, 0xed, 0xd9, 0x19, 0xc3,
	0xce, 0x0f, 0x64, 0x55, 0x3b, 0x53, 0x5f, 0xcf, 0xd6, 0x78, 0xc3, 0x0b, 0xdd, 0xd1, 0xb4, 0xff,
	0xce, 0x60, 0xf5, 0x46, 0xbd, 0xc4, 0x0f, 0x7e, 0x0b, 0x4c, 0xe1, 0x27, 0xf5, 0xd8, 0x92, 0x12,
	0x8b, 0x32, 0xab, 0x98, 0xdc, 0x24, 0xd0, 0x28, 0x7e, 0x0d, 0x1b, 0x63, 0x15, 0xda, 0x30, 0xcb,
	0xca, 0xac, 0x2a, 0xe4, 0x3a, 0x9e, 0x1b, 0xc5, 0xef, 0x01, 0x48, 0x77, 0x47, 0x6c, 0x69, 0x3a,
	0x18, 0x91, 0x97, 0x79, 0xc5, 0x24, 0x8b, 0xa4, 0x99, 0x0e, 0x86, 0x3f, 0xc0, 0x16, 0xbf, 0x66,
	0xb2, 0xd8, 0x7a, 0xd2, 0x28, 0x8a, 0x68, 0x0c, 0x09, 0xbd, 0x93, 0xc6, 0xb0, 0xb7, 0x1f, 0x09,
	0x27, 0x1f, 0xbc, 0x97, 0x69, 0x6f, 0x02, 0x8d, 0xe2, 0x1c, 0x8a, 0xc1, 0x38, 0x2f, 0x56, 0xe5,
	0xa2, 0x62, 0x32, 0x6a, 0xfe, 0x04, 0x97, 0x69, 0xa1, 0x42, 0xdf, 0xd1, 0xd8, 0x8e, 0xe4, 0xbc,
	0x58, 0x97, 0x79, 0xb5, 0x7d, 0xbc, 0xaa, 0x43, 0xab, 0x3a, 0x35, 0xaa, 0x9b, 0x73, 0x08, 0xb9,
	0x8b, 0x0f, 0x9e, 0xe3, 0xfd, 0x17, 0x72, 0xfe, 0xe6, 0x15, 0xd8, 0xdf, 0x94, 0xdf, 0x01, 0x0b,
	0xd9, 0x9c, 0xef, 0xf4, 0xfc, 0xdb, 0xfc, 0x1f, 0xf0, 0x0b, 0xc8, 0x4f, 0x96, 0x62, 0x6b, 0x26,
	0x83, 0x0c, 0xa1, 0xba, 0x93, 0x1f, 0x44, 0x1e, 0x51, 0xd4, 0xfb, 0x3a, 0xfd, 0xa3, 0x9b, 0xc3,
	0xb4, 0x37, 0x0a, 0xa3, 0xd1, 0x52, 0x46, 0x1d, 0x3c, 0xb4, 0x3b, 0x9e, 0x3d, 0xb4, 0x3b, 0xfe,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x63, 0x78, 0x5b, 0xea, 0x90, 0x01, 0x00, 0x00,
}
