// Code generated by protoc-gen-go. DO NOT EDIT.
// source: third_flow_report.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ThirdFlowReportReq struct {
	DeviceFlows          []*ThirdFlowReportReq_DeviceFlow `protobuf:"bytes,1,rep,name=device_flows,json=deviceFlows" json:"device_flows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ThirdFlowReportReq) Reset()         { *m = ThirdFlowReportReq{} }
func (m *ThirdFlowReportReq) String() string { return proto.CompactTextString(m) }
func (*ThirdFlowReportReq) ProtoMessage()    {}
func (*ThirdFlowReportReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_57c4d74434ba23ef, []int{0}
}

func (m *ThirdFlowReportReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThirdFlowReportReq.Unmarshal(m, b)
}
func (m *ThirdFlowReportReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThirdFlowReportReq.Marshal(b, m, deterministic)
}
func (m *ThirdFlowReportReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThirdFlowReportReq.Merge(m, src)
}
func (m *ThirdFlowReportReq) XXX_Size() int {
	return xxx_messageInfo_ThirdFlowReportReq.Size(m)
}
func (m *ThirdFlowReportReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ThirdFlowReportReq.DiscardUnknown(m)
}

var xxx_messageInfo_ThirdFlowReportReq proto.InternalMessageInfo

func (m *ThirdFlowReportReq) GetDeviceFlows() []*ThirdFlowReportReq_DeviceFlow {
	if m != nil {
		return m.DeviceFlows
	}
	return nil
}

type ThirdFlowReportReq_DeviceFlow struct {
	DeviceId             *string  `protobuf:"bytes,1,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
	Channel              *string  `protobuf:"bytes,2,req,name=channel" json:"channel,omitempty"`
	Date                 *string  `protobuf:"bytes,3,req,name=date" json:"date,omitempty"`
	TrackFlow            *uint64  `protobuf:"varint,4,req,name=track_flow,json=trackFlow" json:"track_flow,omitempty"`
	ImgFlow              *uint64  `protobuf:"varint,5,req,name=img_flow,json=imgFlow" json:"img_flow,omitempty"`
	ImgNum               *int32   `protobuf:"varint,6,req,name=img_num,json=imgNum" json:"img_num,omitempty"`
	AppDownstream        *uint64  `protobuf:"varint,7,opt,name=app_downstream,json=appDownstream" json:"app_downstream,omitempty"`
	AppUpstream          *uint64  `protobuf:"varint,8,opt,name=app_upstream,json=appUpstream" json:"app_upstream,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThirdFlowReportReq_DeviceFlow) Reset()         { *m = ThirdFlowReportReq_DeviceFlow{} }
func (m *ThirdFlowReportReq_DeviceFlow) String() string { return proto.CompactTextString(m) }
func (*ThirdFlowReportReq_DeviceFlow) ProtoMessage()    {}
func (*ThirdFlowReportReq_DeviceFlow) Descriptor() ([]byte, []int) {
	return fileDescriptor_57c4d74434ba23ef, []int{0, 0}
}

func (m *ThirdFlowReportReq_DeviceFlow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThirdFlowReportReq_DeviceFlow.Unmarshal(m, b)
}
func (m *ThirdFlowReportReq_DeviceFlow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThirdFlowReportReq_DeviceFlow.Marshal(b, m, deterministic)
}
func (m *ThirdFlowReportReq_DeviceFlow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThirdFlowReportReq_DeviceFlow.Merge(m, src)
}
func (m *ThirdFlowReportReq_DeviceFlow) XXX_Size() int {
	return xxx_messageInfo_ThirdFlowReportReq_DeviceFlow.Size(m)
}
func (m *ThirdFlowReportReq_DeviceFlow) XXX_DiscardUnknown() {
	xxx_messageInfo_ThirdFlowReportReq_DeviceFlow.DiscardUnknown(m)
}

var xxx_messageInfo_ThirdFlowReportReq_DeviceFlow proto.InternalMessageInfo

func (m *ThirdFlowReportReq_DeviceFlow) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *ThirdFlowReportReq_DeviceFlow) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

func (m *ThirdFlowReportReq_DeviceFlow) GetDate() string {
	if m != nil && m.Date != nil {
		return *m.Date
	}
	return ""
}

func (m *ThirdFlowReportReq_DeviceFlow) GetTrackFlow() uint64 {
	if m != nil && m.TrackFlow != nil {
		return *m.TrackFlow
	}
	return 0
}

func (m *ThirdFlowReportReq_DeviceFlow) GetImgFlow() uint64 {
	if m != nil && m.ImgFlow != nil {
		return *m.ImgFlow
	}
	return 0
}

func (m *ThirdFlowReportReq_DeviceFlow) GetImgNum() int32 {
	if m != nil && m.ImgNum != nil {
		return *m.ImgNum
	}
	return 0
}

func (m *ThirdFlowReportReq_DeviceFlow) GetAppDownstream() uint64 {
	if m != nil && m.AppDownstream != nil {
		return *m.AppDownstream
	}
	return 0
}

func (m *ThirdFlowReportReq_DeviceFlow) GetAppUpstream() uint64 {
	if m != nil && m.AppUpstream != nil {
		return *m.AppUpstream
	}
	return 0
}

type ThirdFlowReportRsp struct {
	Code                 *int32   `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Msg                  *string  `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThirdFlowReportRsp) Reset()         { *m = ThirdFlowReportRsp{} }
func (m *ThirdFlowReportRsp) String() string { return proto.CompactTextString(m) }
func (*ThirdFlowReportRsp) ProtoMessage()    {}
func (*ThirdFlowReportRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_57c4d74434ba23ef, []int{1}
}

func (m *ThirdFlowReportRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThirdFlowReportRsp.Unmarshal(m, b)
}
func (m *ThirdFlowReportRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThirdFlowReportRsp.Marshal(b, m, deterministic)
}
func (m *ThirdFlowReportRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThirdFlowReportRsp.Merge(m, src)
}
func (m *ThirdFlowReportRsp) XXX_Size() int {
	return xxx_messageInfo_ThirdFlowReportRsp.Size(m)
}
func (m *ThirdFlowReportRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ThirdFlowReportRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ThirdFlowReportRsp proto.InternalMessageInfo

func (m *ThirdFlowReportRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *ThirdFlowReportRsp) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ThirdFlowReportReq)(nil), "main.ThirdFlowReportReq")
	proto.RegisterType((*ThirdFlowReportReq_DeviceFlow)(nil), "main.ThirdFlowReportReq.DeviceFlow")
	proto.RegisterType((*ThirdFlowReportRsp)(nil), "main.ThirdFlowReportRsp")
}

func init() { proto.RegisterFile("third_flow_report.proto", fileDescriptor_57c4d74434ba23ef) }

var fileDescriptor_57c4d74434ba23ef = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0x95, 0x34, 0xfd, 0xc9, 0x49, 0xbf, 0x4f, 0xc8, 0x4b, 0x0d, 0x08, 0x29, 0x14, 0x21,
	0x65, 0xca, 0xc0, 0xc8, 0x5c, 0x55, 0x62, 0x61, 0xb0, 0x60, 0x8e, 0xac, 0xd8, 0xa4, 0x16, 0x71,
	0x6c, 0x1c, 0x87, 0x5c, 0x28, 0xb7, 0xc2, 0x05, 0x20, 0x9f, 0x86, 0x32, 0x74, 0x7b, 0xf3, 0x3e,
	0xcf, 0x89, 0x7d, 0x0c, 0x1b, 0x7f, 0x50, 0x4e, 0x54, 0x6f, 0xad, 0x19, 0x2b, 0x27, 0xad, 0x71,
	0xbe, 0xb4, 0xce, 0x78, 0x43, 0x12, 0xcd, 0x55, 0xb7, 0xfd, 0x8a, 0x81, 0xbc, 0x04, 0x63, 0xdf,
	0x9a, 0x91, 0x21, 0x67, 0xf2, 0x83, 0xec, 0x61, 0x2d, 0xe4, 0xa7, 0xaa, 0x25, 0x0e, 0xf6, 0x34,
	0xca, 0x67, 0x45, 0xf6, 0x70, 0x57, 0x86, 0x99, 0xf2, 0xdc, 0x2f, 0x77, 0x28, 0x63, 0x97, 0x89,
	0x53, 0xee, 0xaf, 0xbe, 0x23, 0x80, 0x3f, 0x46, 0xae, 0x21, 0x9d, 0x7e, 0xab, 0x04, 0x8d, 0xf2,
	0xb8, 0x48, 0xd9, 0xea, 0x58, 0x3c, 0x09, 0x42, 0x61, 0x59, 0x1f, 0x78, 0xd7, 0xc9, 0x96, 0xc6,
	0x88, 0x7e, 0x3f, 0x09, 0x81, 0x44, 0x70, 0x2f, 0xe9, 0x0c, 0x6b, 0xcc, 0xe4, 0x06, 0xc0, 0x3b,
	0x5e, 0xbf, 0xe3, 0x05, 0x69, 0x92, 0xc7, 0x45, 0xc2, 0x52, 0x6c, 0xf0, 0xa4, 0x4b, 0x58, 0x29,
	0xdd, 0x1c, 0xe1, 0x1c, 0xe1, 0x52, 0xe9, 0x06, 0xd1, 0x06, 0x42, 0xac, 0xba, 0x41, 0xd3, 0x45,
	0x1e, 0x17, 0x73, 0xb6, 0x50, 0xba, 0x79, 0x1e, 0x34, 0xb9, 0x87, 0xff, 0xdc, 0xda, 0x4a, 0x98,
	0xb1, 0xeb, 0xbd, 0x93, 0x5c, 0xd3, 0x65, 0x1e, 0x15, 0x09, 0xfb, 0xc7, 0xad, 0xdd, 0x9d, 0x4a,
	0x72, 0x0b, 0xeb, 0xa0, 0x0d, 0x76, 0x92, 0x56, 0x28, 0x65, 0xdc, 0xda, 0xd7, 0xa9, 0xda, 0x3e,
	0x9e, 0x3f, 0x6a, 0x6f, 0xc3, 0x1a, 0xb5, 0x11, 0x12, 0x17, 0x9f, 0x33, 0xcc, 0xe4, 0x02, 0x66,
	0xba, 0x6f, 0xa6, 0x85, 0x43, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x25, 0xa8, 0x46, 0x88, 0xb1,
	0x01, 0x00, 0x00,
}
